services:
  web:
    image: node:20-slim
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: bash -lc "npm ci || npm i && npm run dev -- --hostname 0.0.0.0 --webpack"
    environment:
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000

volumes:
  node_modules:
